# Generated by Django 5.2.1 on 2025-05-14 17:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0005_remove_animal_country_remove_animal_employee_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-pub_date'], 'verbose_name': 'News', 'verbose_name_plural': 'News'},
        ),
        migrations.AlterModelOptions(
            name='companyinfo',
            options={'verbose_name': 'Info about company', 'verbose_name_plural': 'Info about company'},
        ),
        migrations.AlterModelOptions(
            name='employeepositions',
            options={'verbose_name': 'Position', 'verbose_name_plural': 'Position'},
        ),
        migrations.AlterModelOptions(
            name='faq',
            options={'ordering': ['-date_added'], 'verbose_name': 'QA', 'verbose_name_plural': 'Terms dictionary'},
        ),
        migrations.AlterModelOptions(
            name='privacypolicy',
            options={},
        ),
        migrations.AlterModelOptions(
            name='promocode',
            options={'ordering': ['-created_at'], 'verbose_name': 'Promocode', 'verbose_name_plural': 'Promocodes'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-pub_date'], 'verbose_name': 'Recall', 'verbose_name_plural': 'Recall'},
        ),
        migrations.AlterModelOptions(
            name='vacancy',
            options={'ordering': ['-created_at'], 'verbose_name': 'Vacancy', 'verbose_name_plural': 'Vacancy'},
        ),
        migrations.RemoveField(
            model_name='privacypolicy',
            name='content',
        ),
        migrations.RemoveField(
            model_name='privacypolicy',
            name='last_updated',
        ),
        migrations.AlterField(
            model_name='article',
            name='full_text',
            field=models.TextField(verbose_name='Full text'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(upload_to='articles/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='article',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Published'),
        ),
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date published'),
        ),
        migrations.AlterField(
            model_name='article',
            name='short_description',
            field=models.CharField(max_length=200, verbose_name='Summary'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Header'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='about_text',
            field=models.TextField(verbose_name='About company'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='history',
            field=models.TextField(blank=True, verbose_name='History'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='logo',
            field=models.ImageField(upload_to='company/', verbose_name='Logotype'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='requisites',
            field=models.TextField(verbose_name='Props'),
        ),
        migrations.AlterField(
            model_name='employeepositions',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=models.TextField(verbose_name='Answer'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='date_added',
            field=models.DateField(auto_now_add=True, verbose_name='Date added'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question',
            field=models.CharField(max_length=255, verbose_name='Question'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='discount',
            field=models.PositiveIntegerField(verbose_name='Sale size (%)'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='expiry_date',
            field=models.DateField(verbose_name='Expiry date'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='review',
            name='author_name',
            field=models.CharField(max_length=100, verbose_name='Author name'),
        ),
        migrations.AlterField(
            model_name='review',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Published'),
        ),
        migrations.AlterField(
            model_name='review',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date published'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[(1, '1 - Awful'), (2, '2 - Bad'), (3, '3 - OK'), (4, '4 - Good'), (5, '5 - Perfect')], verbose_name='Mark'),
        ),
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.TextField(verbose_name='Recall text'),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='requirements',
            field=models.TextField(verbose_name='Requerments'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='salary',
            field=models.CharField(blank=True, max_length=100, verbose_name='Salary'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Vacancy name'),
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('photo', models.ImageField(upload_to='contacts/', verbose_name='Photo')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('description', models.TextField(verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='zoo.employeepositions', verbose_name='Position')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
            },
        ),
        migrations.DeleteModel(
            name='Employees',
        ),
    ]
