# Generated by Django 5.2.1 on 2025-05-19 08:49

import zoo.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0010_extraservice_created_at_extraservice_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, help_text='Формат: +375 (29) XXX-XX-XX', max_length=20, null=True, validators=[zoo.validators.validate_belarus_phone_number]),
        ),
    ]
