# Generated by Django 5.2.1 on 2025-05-20 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_alter_employee_user'),
        ('zoo', '0011_alter_user_phone'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Review',
            new_name='Recall',
        ),
        migrations.AlterField(
            model_name='contacts',
            name='position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.employeeposition', verbose_name='Position'),
        ),
        migrations.DeleteModel(
            name='EmployeePositions',
        ),
    ]
