# Generated by Django 5.2.1 on 2025-05-13 17:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('number', models.SmallIntegerField()),
                ('has_swimming', models.BooleanField()),
                ('has_heating', models.BooleanField()),
                ('square', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
