# Generated by Django 5.2.1 on 2025-05-16 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animalfoodtype',
            name='time',
        ),
        migrations.AddField(
            model_name='animalfoodtype',
            name='times',
            field=models.IntegerField(default=0),
        ),
    ]
