# Generated by Django 5.2.1 on 2025-05-13 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0003_animalfamily_country_employeepositions_foodtype_room_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='room',
        ),
    ]
