# Generated by Django 5.2.1 on 2025-05-20 11:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_alter_employee_user'),
        ('zoo', '0012_rename_review_recall_alter_contacts_position_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recall',
            options={'ordering': ['-pub_date'], 'verbose_name': 'Recall', 'verbose_name_plural': 'Recalls'},
        ),
        migrations.AlterField(
            model_name='recall',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Published'),
        ),
        migrations.AlterField(
            model_name='recall',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.employeeposition'),
        ),
    ]
