# Generated by Django 5.2.1 on 2025-05-20 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0013_alter_recall_options_alter_recall_is_published_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contacts',
        ),
    ]
