# Generated by Django 5.2.1 on 2025-09-12 07:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0015_alter_faq_options_faq_answered_by_faq_asked_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('website', models.URLField()),
                ('logo', models.ImageField(upload_to='partners/')),
            ],
            options={
                'verbose_name': 'Partner Company',
                'verbose_name_plural': 'Partner Companies',
            },
        ),
        migrations.AlterField(
            model_name='ticket',
            name='promo_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='zoo.promocode'),
        ),
    ]
