# Generated by Django 5.2.1 on 2025-05-13 17:06

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AnimalFamily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AnimalFoodType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('food_name', models.CharField(max_length=20)),
                ('portion', models.FloatField(default=0.0)),
                ('time', models.TimeField(default=datetime.time)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('receipt_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('birthday', models.DateTimeField(default=django.utils.timezone.now)),
                ('facts', models.TextField()),
                ('photo', models.ImageField(upload_to='photos/animals/')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='news', to='employee.employee')),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='animals', related_query_name='animals', to='room.room')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='country', to='animal.animalcountry')),
                ('family', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='family', to='animal.animalfamily')),
                ('food_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='food_type', to='animal.animalfoodtype')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
