# Generated by Django 5.2.1 on 2025-05-16 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0002_remove_animalfoodtype_time_animalfoodtype_times'),
        ('employee', '0003_alter_employee_phone_alter_employee_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='animal', to='employee.employee'),
        ),
    ]
