# Generated by Django 5.2.1 on 2025-05-17 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0003_alter_animal_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='animals', to='animal.animalcountry'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='family',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='animals', to='animal.animalfamily'),
        ),
    ]
